import { sqliteTable, AnySQLiteColumn, integer, text, numeric, foreignKey, index, real, uniqueIndex } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const configGlobal = sqliteTable("config_global", {
	id: integer().primaryKey({ autoIncrement: true }),
	chave: text().notNull(),
	valor: text().notNull(),
	descricao: text(),
	updatedBy: integer("updated_by"),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const diretorias = sqliteTable("diretorias", {
	id: integer().primaryKey({ autoIncrement: true }),
	codigo: text().notNull(),
	nome: text().notNull(),
	sigla: text().notNull(),
	ativo: integer().default(1).notNull(),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	descricao: text(),
	updatedAt: numeric("updated_at"),
	diretorResponsavelId: integer("diretor_responsavel_id"),
	ordem: integer().default(99),
});

export const areas = sqliteTable("areas", {
	id: integer().primaryKey({ autoIncrement: true }),
	diretoriaId: integer("diretoria_id").notNull().references(() => diretorias.id),
	codigo: text().notNull(),
	nome: text().notNull(),
	sigla: text().notNull(),
	ativo: integer().default(1).notNull(),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	descricao: text(),
	updatedAt: numeric("updated_at"),
});

export const perfis = sqliteTable("perfis", {
	id: integer().primaryKey({ autoIncrement: true }),
	codigo: text().notNull(),
	nome: text().notNull(),
	descricao: text(),
	permissoes: text().default("{}").notNull(),
	ativo: integer().default(1).notNull(),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const usuarios = sqliteTable("usuarios", {
	id: integer().primaryKey({ autoIncrement: true }),
	cpf: text().notNull(),
	nome: text().notNull(),
	email: text().notNull(),
	senhaHash: text("senha_hash").notNull(),
	cargo: text(),
	diretoriaId: integer("diretoria_id").references(() => diretorias.id),
	areaId: integer("area_id").references(() => areas.id),
	perfilId: integer("perfil_id").notNull().references(() => perfis.id),
	ativo: integer().default(1).notNull(),
	ultimoLogin: numeric("ultimo_login"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const sessoes = sqliteTable("sessoes", {
	id: integer().primaryKey({ autoIncrement: true }),
	usuarioId: integer("usuario_id").notNull().references(() => usuarios.id),
	token: text().notNull(),
	ip: text(),
	userAgent: text("user_agent"),
	expiresAt: numeric("expires_at").notNull(),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const projetos = sqliteTable("projetos", {
	id: integer().primaryKey({ autoIncrement: true }),
	codigo: text().notNull(),
	nome: text().notNull(),
	solicitanteId: integer("solicitante_id").notNull().references(() => usuarios.id),
	diretoriaId: integer("diretoria_id").notNull().references(() => diretorias.id),
	areaId: integer("area_id").notNull().references(() => areas.id),
	pontoFocal: text("ponto_focal"),
	contato: text(),
	objetivo: text().notNull(),
	descricao: text(),
	beneficios: text(),
	status: text().default("PROPOSTA").notNull(),
	classificacao: text(),
	complexidade: text(),
	prioridade: text().default("MEDIA"),
	gerenteId: integer("gerente_id").references(() => usuarios.id),
	capexAprovado: real("capex_aprovado"),
	opexAprovado: real("opex_aprovado"),
	dataInicioPrev: numeric("data_inicio_prev"),
	dataFimPrev: numeric("data_fim_prev"),
	dataGolive: numeric("data_golive"),
	ativo: integer().default(1).notNull(),
	createdBy: integer("created_by").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
	justificativa: text(),
	dataConclusaoReal: text("data_conclusao_real"),
	horaConclusao: text("hora_conclusao"),
	responsavelConclusao: text("responsavel_conclusao"),
	motivoConclusao: text("motivo_conclusao"),
	checklistConclusao: text("checklist_conclusao"),
	projetoMigrado: integer("projeto_migrado").default(0),
	motivoPausaId: integer("motivo_pausa_id"),
	pmoResponsavel: text("pmo_responsavel"),
	tipoBeneficio: text("tipo_beneficio"),
	cronogramaPendente: integer("cronograma_pendente").default(0),
	migradoEm: text("migrado_em"),
	migradoPor: integer("migrado_por"),
	dataPausa: text("data_pausa"),
	usuarioPausa: integer("usuario_pausa"),
	pmoResponsavelId: integer("pmo_responsavel_id"),
	origemDados: text("origem_dados"),
	arquivoOrigem: text("arquivo_origem"),
	dataBaseEntrega: text("data_base_entrega"),
	dataBaseEntregaDefinidaEm: text("data_base_entrega_definida_em"),
},
(table) => [
	index("idx_projetos_gerente").on(table.gerenteId),
	index("idx_projetos_diretoria").on(table.diretoriaId),
	index("idx_projetos_status").on(table.status),
]);

export const projetoStatusHistorico = sqliteTable("projeto_status_historico", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	statusDe: text("status_de").notNull(),
	statusPara: text("status_para").notNull(),
	motivo: text(),
	usuarioId: integer("usuario_id").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const projetoPrioridadeHistorico = sqliteTable("projeto_prioridade_historico", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	prioridadeDe: text("prioridade_de").notNull(),
	prioridadePara: text("prioridade_para").notNull(),
	motivo: text(),
	usuarioId: integer("usuario_id").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const projetoAreas = sqliteTable("projeto_areas", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	areaId: integer("area_id").notNull().references(() => areas.id),
	responsavelId: integer("responsavel_id").references(() => usuarios.id),
	papel: text(),
	ativo: integer().default(1).notNull(),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const tapVersoes = sqliteTable("tap_versoes", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	versao: integer().notNull(),
	label: text().notNull(),
	faseOrigem: text("fase_origem").notNull(),
	escopoInicial: text("escopo_inicial"),
	escopoFora: text("escopo_fora"),
	beneficiosTap: text("beneficios_tap"),
	areasImpactadas: text("areas_impactadas"),
	objetivoDetalhado: text("objetivo_detalhado"),
	descricaoSolucao: text("descricao_solucao"),
	premissas: text(),
	restricoes: text(),
	riscosIniciais: text("riscos_iniciais"),
	investimentoTotal: real("investimento_total"),
	roiPrevisto: real("roi_previsto"),
	vpl: real(),
	tir: real(),
	paybackMeses: real("payback_meses"),
	criadoPor: integer("criado_por").notNull().references(() => usuarios.id),
	aprovadoPor: integer("aprovado_por").references(() => usuarios.id),
	aprovadoEm: numeric("aprovado_em"),
	status: text().default("RASCUNHO"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	situacaoAtual: text("situacao_atual"),
	escopoFisico: text("escopo_fisico"),
	escopoSistemico: text("escopo_sistemico"),
	escopoProcesso: text("escopo_processo"),
	setoresEnvolvidos: text("setores_envolvidos"),
	etapasProjeto: text("etapas_projeto"),
	entregaveis: text(),
	pontosAtencao: text("pontos_atencao"),
	pontosDefinir: text("pontos_definir"),
	updatedAt: numeric("updated_at"),
	dataLimiteTap: text("data_limite_tap"),
},
(table) => [
	index("idx_tap_projeto").on(table.projetoId, table.versao),
]);

export const triagens = sqliteTable("triagens", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	escopoInicial: text("escopo_inicial"),
	escopoFora: text("escopo_fora"),
	beneficios: text(),
	areasImpactadas: text("areas_impactadas"),
	classificacao: text(),
	complexidade: text(),
	prioridade: text(),
	observacoes: text(),
	responsavelId: integer("responsavel_id").references(() => usuarios.id),
	concluida: integer().default(0),
	createdBy: integer("created_by").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const comites = sqliteTable("comites", {
	id: integer().primaryKey({ autoIncrement: true }),
	titulo: text().notNull(),
	tipo: text().default("IDEIAS").notNull(),
	dataRealizacao: numeric("data_realizacao").notNull(),
	local: text(),
	pauta: text(),
	decisaoGeral: text("decisao_geral"),
	status: text().default("AGENDADO"),
	createdBy: integer("created_by").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
	hora: text(),
	periodoInicio: text("periodo_inicio"),
	periodoFim: text("periodo_fim"),
	descricao: text(),
	resumoExecutivoIa: text("resumo_executivo_ia"),
	resumoIaGeradoEm: text("resumo_ia_gerado_em"),
	resumoExecutivoIaJson: text("resumo_executivo_ia_json"),
	diretoriasIds: text("diretorias_ids"),
	observacoes: text(),
});

export const comiteParticipantes = sqliteTable("comite_participantes", {
	id: integer().primaryKey({ autoIncrement: true }),
	comiteId: integer("comite_id").notNull().references(() => comites.id),
	usuarioId: integer("usuario_id").references(() => usuarios.id),
	nomeExterno: text("nome_externo"),
	cargo: text(),
	presente: integer().default(0),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	confirmado: integer().default(0),
});

export const comiteProjetos = sqliteTable("comite_projetos", {
	id: integer().primaryKey({ autoIncrement: true }),
	comiteId: integer("comite_id").notNull().references(() => comites.id),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	pautaItem: text("pauta_item"),
	decisao: text(),
	observacoes: text(),
	snapPrioridade: text("snap_prioridade"),
	snapComplexidade: text("snap_complexidade"),
	snapInvestimento: real("snap_investimento"),
	snapRoi: real("snap_roi"),
	snapPayback: real("snap_payback"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	ordemPauta: integer("ordem_pauta").default(0),
	tempoPrevisto: integer("tempo_previsto"),
});

export const comiteDocumentos = sqliteTable("comite_documentos", {
	id: integer().primaryKey({ autoIncrement: true }),
	comiteId: integer("comite_id").notNull().references(() => comites.id),
	nome: text().notNull(),
	caminho: text().notNull(),
	tipo: text(),
	createdBy: integer("created_by").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const viabilidade = sqliteTable("viabilidade", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	versao: integer().default(1).notNull(),
	selic: real(),
	taxaDesconto: real("taxa_desconto"),
	inflacao: real(),
	investimentoTotal: real("investimento_total"),
	receitasPrevistas: text("receitas_previstas"),
	custosPrevistos: text("custos_previstos"),
	economiaPrevista: text("economia_prevista"),
	roi: real(),
	vpl: real(),
	tir: real(),
	paybackMeses: real("payback_meses"),
	impactoOperacional: text("impacto_operacional"),
	recursosNecessarios: text("recursos_necessarios"),
	mudancaProcesso: text("mudanca_processo"),
	tecnologias: text(),
	"integrações": text("integrações"),
	infraestrutura: text(),
	riscos: text(),
	impactos: text(),
	dataInicioPrev: numeric("data_inicio_prev"),
	dataFimPrev: numeric("data_fim_prev"),
	marcos: text(),
	status: text().default("RASCUNHO"),
	criadoPor: integer("criado_por").notNull().references(() => usuarios.id),
	aprovadoPor: integer("aprovado_por").references(() => usuarios.id),
	aprovadoEm: numeric("aprovado_em"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
	resumoExecutivo: text("resumo_executivo"),
	sistemasEnvolvidos: text("sistemas_envolvidos"),
	dependenciaFornecedores: text("dependencia_fornecedores"),
	recomendacao: text(),
	justificativaRecomendacao: text("justificativa_recomendacao"),
	conclusao: text(),
	capex: real(),
	opex: real(),
	opexPeriodicidade: text("opex_periodicidade").default("MENSAL"),
	economiaEstimada: real("economia_estimada"),
	economiaPeriodicidade: text("economia_periodicidade").default("MENSAL"),
	tipoPayback: text("tipo_payback").default("QUALITATIVO"),
	paybackInformado: real("payback_informado"),
	paybackUnidade: text("payback_unidade").default("MESES"),
	condicoesAprovacao: text("condicoes_aprovacao"),
	complexidadeTecnica: text("complexidade_tecnica"),
	tipoPaybackQuantitativo: integer("tipo_payback_quantitativo"),
	tipoPaybackQualitativo: integer("tipo_payback_qualitativo"),
	beneficiosEsperados: text("beneficios_esperados"),
	baselineValor: real("baseline_valor"),
	metaValor: real("meta_valor"),
	tipoIndicador: text("tipo_indicador").default("ABSOLUTO"),
	economiaMensalEsperada: real("economia_mensal_esperada"),
	ganhoTarefaAtivo: integer("ganho_tarefa_ativo").default(0),
	ganhoTarefaSalario: real("ganho_tarefa_salario"),
	ganhoTarefaHorasAntes: real("ganho_tarefa_horas_antes"),
	ganhoTarefaHorasDepois: real("ganho_tarefa_horas_depois"),
	ganhoTarefaFreqMensal: real("ganho_tarefa_freq_mensal").default(1),
	hcAtivo: integer("hc_ativo").default(0),
	hcQuantidade: integer("hc_quantidade").default(1),
	hcSalarioMensal: real("hc_salario_mensal"),
	hcEncargosPct: real("hc_encargos_pct"),
	hcBeneficiosMensais: real("hc_beneficios_mensais"),
	hcOutrosMensais: real("hc_outros_mensais"),
	horasAnalistasAtivo: integer("horas_analistas_ativo").default(0),
	horasAnalistasJson: text("horas_analistas_json"),
	horasAnalistasTotal: real("horas_analistas_total"),
});

export const financeiroLancamentos = sqliteTable("financeiro_lancamentos", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	tipo: text().notNull(),
	categoria: text().notNull(),
	descricao: text().notNull(),
	fornecedor: text(),
	numeroDoc: text("numero_doc"),
	valor: real().notNull(),
	dataLancamento: numeric("data_lancamento").notNull(),
	competencia: text(),
	observacoes: text(),
	arquivoPath: text("arquivo_path"),
	criadoPor: integer("criado_por").notNull().references(() => usuarios.id),
	aprovadoPor: integer("aprovado_por").references(() => usuarios.id),
	aprovadoEm: numeric("aprovado_em"),
	status: text().default("PENDENTE"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	itemId: integer("item_id"),
},
(table) => [
	index("idx_lancamentos_projeto").on(table.projetoId, table.tipo),
]);

export const roiAcompanhamento = sqliteTable("roi_acompanhamento", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	competencia: text().notNull(),
	receitaReal: real("receita_real"),
	custoReal: real("custo_real"),
	economiaReal: real("economia_real"),
	observacoes: text(),
	criadoPor: integer("criado_por").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const estruturacao = sqliteTable("estruturacao", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	gerenteId: integer("gerente_id").references(() => usuarios.id),
	patrocinadorId: integer("patrocinador_id").references(() => usuarios.id),
	metodologia: text(),
	escopoDetalhado: text("escopo_detalhado"),
	entregas: text(),
	observacoes: text(),
	concluida: integer().default(0),
	createdBy: integer("created_by").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const cronogramas = sqliteTable("cronogramas", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	versao: integer().default(1).notNull(),
	label: text().notNull(),
	isBaseline: integer("is_baseline").default(0),
	status: text().default("ATIVO"),
	motivoReplano: text("motivo_replano"),
	aprovadoPor: integer("aprovado_por").references(() => usuarios.id),
	aprovadoEm: numeric("aprovado_em"),
	criadoPor: integer("criado_por").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	fonteImportacao: text("fonte_importacao").default("MANUAL"),
	arquivoOrigem: text("arquivo_origem"),
	modo: text().default("CENTRALIZADO").notNull(),
	ativo: integer().default(1),
	deletedAt: text("deleted_at"),
	arquivado: integer().default(0),
	arquivadoPor: integer("arquivado_por").references(() => usuarios.id),
	arquivadoEm: text("arquivado_em"),
},
(table) => [
	uniqueIndex("idx_cronogramas_projeto_versao").on(table.projetoId, table.versao),
	index("idx_cronograma_projeto").on(table.projetoId),
]);

export const cronogramaTarefas = sqliteTable("cronograma_tarefas", {
	id: integer().primaryKey({ autoIncrement: true }),
	cronogramaId: integer("cronograma_id").notNull().references(() => cronogramas.id),
	parentId: integer("parent_id"),
	nivel: integer().default(1),
	ordem: integer().default(0),
	codigo: text(),
	nome: text().notNull(),
	responsavelId: integer("responsavel_id").references(() => usuarios.id),
	dataInicio: numeric("data_inicio"),
	dataFim: numeric("data_fim"),
	duracaoDias: integer("duracao_dias"),
	dependencias: text(),
	percentual: integer().default(0),
	bloqueio: integer().default(0),
	motivoBloqueio: text("motivo_bloqueio"),
	status: text().default("NAO_INICIADA"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
	areaId: integer("area_id"),
	tipo: text().default("TAREFA"),
	criticidade: text().default("NORMAL"),
	observacoes: text(),
	motivoAtraso: text("motivo_atraso"),
	dependenciaId: integer("dependencia_id"),
	peso: real().default(1),
	alteradoPor: integer("alterado_por"),
	alteradoEm: text("alterado_em"),
	executorId: integer("executor_id"),
	criadoPor: integer("criado_por"),
	descricao: text(),
	dataConclusao: text("data_conclusao"),
	concluidoPor: integer("concluido_por"),
	prazoStatus: text("prazo_status"),
	responsavelNomeExt: text("responsavel_nome_ext"),
	executorNomeExt: text("executor_nome_ext"),
	ativo: integer().default(1),
	tipoMacro: text("tipo_macro").default("OUTRO"),
	dataFimBaseline: text("data_fim_baseline"),
	dataInicioBaseline: text("data_inicio_baseline"),
	naturezaTarefa: text("natureza_tarefa").default("NORMAL"),
},
(table) => [
	foreignKey(() => ({
			columns: [table.parentId],
			foreignColumns: [table.id],
			name: "cronograma_tarefas_parent_id_cronograma_tarefas_id_fk"
		})),
]);

export const execucaoAtualizacoes = sqliteTable("execucao_atualizacoes", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	tarefaId: integer("tarefa_id").references(() => cronogramaTarefas.id),
	tipo: text().notNull(),
	descricao: text().notNull(),
	percentual: integer(),
	criadoPor: integer("criado_por").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const execucaoArquivos = sqliteTable("execucao_arquivos", {
	id: integer().primaryKey({ autoIncrement: true }),
	atualizacaoId: integer("atualizacao_id").notNull().references(() => execucaoAtualizacoes.id),
	nome: text().notNull(),
	caminho: text().notNull(),
	tipoMime: text("tipo_mime"),
	tamanhoBytes: integer("tamanho_bytes"),
	criadoPor: integer("criado_por").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const notificacoes = sqliteTable("notificacoes", {
	id: integer().primaryKey({ autoIncrement: true }),
	usuarioId: integer("usuario_id").notNull().references(() => usuarios.id),
	projetoId: integer("projeto_id").references(() => projetos.id),
	tipo: text().notNull(),
	titulo: text().notNull(),
	mensagem: text().notNull(),
	lida: integer().default(0),
	lidaEm: numeric("lida_em"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
},
(table) => [
	index("idx_notificacoes_usuario").on(table.usuarioId, table.lida),
]);

export const aprovacoes = sqliteTable("aprovacoes", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	tipo: text().notNull(),
	referenciaId: integer("referencia_id"),
	referenciaTipo: text("referencia_tipo"),
	status: text().default("PENDENTE"),
	solicitanteId: integer("solicitante_id").notNull().references(() => usuarios.id),
	aprovadorId: integer("aprovador_id").references(() => usuarios.id),
	observacaoReq: text("observacao_req"),
	observacaoApr: text("observacao_apr"),
	aprovadoEm: numeric("aprovado_em"),
	prazo: numeric(),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
},
(table) => [
	index("idx_aprovacoes_status").on(table.status, table.aprovadorId),
]);

export const documentos = sqliteTable("documentos", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").references(() => projetos.id),
	tipo: text().notNull(),
	titulo: text().notNull(),
	descricao: text(),
	versao: integer().default(1).notNull(),
	status: text().default("RASCUNHO"),
	geradoAuto: integer("gerado_auto").default(0),
	caminho: text(),
	conteudoJson: text("conteudo_json"),
	criadoPor: integer("criado_por").notNull().references(() => usuarios.id),
	aprovadoPor: integer("aprovado_por").references(() => usuarios.id),
	aprovadoEm: numeric("aprovado_em"),
	publicadoEm: numeric("publicado_em"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const documentosVersoes = sqliteTable("documentos_versoes", {
	id: integer().primaryKey({ autoIncrement: true }),
	documentoId: integer("documento_id").notNull().references(() => documentos.id),
	versao: integer().notNull(),
	status: text(),
	caminho: text(),
	conteudoJson: text("conteudo_json"),
	criadoPor: integer("criado_por").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const encerramentos = sqliteTable("encerramentos", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	licoesAprendidas: text("licoes_aprendidas"),
	roiPrevisto: real("roi_previsto"),
	roiRealizado: real("roi_realizado"),
	paybackPrevisto: real("payback_previsto"),
	paybackRealizado: real("payback_realizado"),
	capexPrevisto: real("capex_previsto"),
	capexRealizado: real("capex_realizado"),
	opexPrevisto: real("opex_previsto"),
	opexRealizado: real("opex_realizado"),
	economiaPrevista: real("economia_prevista"),
	economiaRealizada: real("economia_realizada"),
	avaliacaoGeral: text("avaliacao_geral"),
	recomendacoes: text(),
	criadoPor: integer("criado_por").notNull().references(() => usuarios.id),
	aprovadoPor: integer("aprovado_por").references(() => usuarios.id),
	aprovadoEm: numeric("aprovado_em"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const auditoria = sqliteTable("auditoria", {
	id: integer().primaryKey({ autoIncrement: true }),
	usuarioId: integer("usuario_id").references(() => usuarios.id),
	usuarioNome: text("usuario_nome"),
	acao: text().notNull(),
	entidade: text().notNull(),
	entidadeId: integer("entidade_id"),
	projetoId: integer("projeto_id").references(() => projetos.id),
	descricao: text().notNull(),
	dadosAntes: text("dados_antes"),
	dadosDepois: text("dados_depois"),
	ip: text(),
	userAgent: text("user_agent"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
},
(table) => [
	index("idx_auditoria_usuario").on(table.usuarioId),
	index("idx_auditoria_projeto").on(table.projetoId),
	index("idx_auditoria_entidade").on(table.entidade, table.entidadeId),
]);

export const documentoAprovadores = sqliteTable("documento_aprovadores", {
	id: integer().primaryKey({ autoIncrement: true }),
	tipoDocumento: text("tipo_documento").notNull(),
	usuarioId: integer("usuario_id").notNull().references(() => usuarios.id),
	ordem: integer().default(1),
	obrigatorio: integer().default(1),
	ativo: integer().default(1),
	createdBy: integer("created_by").references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
},
(table) => [
	index("idx_doc_aprovadores_tipo").on(table.tipoDocumento, table.ativo),
]);

export const financeiroAnexos = sqliteTable("financeiro_anexos", {
	id: integer().primaryKey({ autoIncrement: true }),
	lancamentoId: integer("lancamento_id").notNull().references(() => financeiroLancamentos.id),
	nome: text().notNull(),
	caminho: text().notNull(),
	tipoMime: text("tipo_mime"),
	tamanhoBytes: integer("tamanho_bytes"),
	tipoAnexo: text("tipo_anexo").default("NF"),
	criadoPor: integer("criado_por").notNull().references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
},
(table) => [
	index("idx_financeiro_anexos").on(table.lancamentoId),
]);

export const configStatusProjeto = sqliteTable("config_status_projeto", {
	id: integer().primaryKey({ autoIncrement: true }),
	codigo: text().notNull(),
	label: text().notNull(),
	descricao: text(),
	cor: text().default("#6B7280"),
	ordem: integer().default(0),
	ativo: integer().default(1),
	isInitial: integer("is_initial").default(0),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`"),
	updatedAt: text("updated_at").default("sql`(CURRENT_TIMESTAMP)`"),
});

export const projetoHistoricoAlteracoes = sqliteTable("projeto_historico_alteracoes", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull(),
	usuarioId: integer("usuario_id"),
	usuarioNome: text("usuario_nome"),
	campo: text().notNull(),
	valorAnterior: text("valor_anterior"),
	valorNovo: text("valor_novo"),
	acao: text().default("UPDATE"),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`"),
});

export const workflowAprovacao = sqliteTable("workflow_aprovacao", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull(),
	tipo: text().notNull(),
	referenciaId: integer("referencia_id").notNull(),
	etapaAtual: integer("etapa_atual").default(1),
	status: text().default("EM_ANDAMENTO"),
	criadoPor: integer("criado_por"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	modeloId: integer("modelo_id"),
});

export const workflowEtapas = sqliteTable("workflow_etapas", {
	id: integer().primaryKey({ autoIncrement: true }),
	workflowId: integer("workflow_id").notNull(),
	ordem: integer().notNull(),
	usuarioId: integer("usuario_id").notNull(),
	usuarioNome: text("usuario_nome").notNull(),
	tipo: text().notNull(),
	status: text().default("PENDENTE"),
	observacao: text(),
	respondidoEm: numeric("respondido_em"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const workflowTiposParticipacao = sqliteTable("workflow_tipos_participacao", {
	id: integer().primaryKey({ autoIncrement: true }),
	nome: text().notNull(),
	codigo: text().notNull(),
	descricao: text(),
	ativo: integer().default(1),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const workflowModelos = sqliteTable("workflow_modelos", {
	id: integer().primaryKey({ autoIncrement: true }),
	nome: text().notNull(),
	descricao: text(),
	ativo: integer().default(1),
	criadoPor: integer("criado_por"),
	criadoPorNome: text("criado_por_nome"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const workflowModeloEtapas = sqliteTable("workflow_modelo_etapas", {
	id: integer().primaryKey({ autoIncrement: true }),
	modeloId: integer("modelo_id").notNull(),
	ordem: integer().notNull(),
	usuarioId: integer("usuario_id").notNull(),
	usuarioNome: text("usuario_nome").notNull(),
	tipo: text().notNull(),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const configContasContabeis = sqliteTable("config_contas_contabeis", {
	id: integer().primaryKey({ autoIncrement: true }),
	codigo: text().notNull(),
	descricao: text().notNull(),
	tipo: text().default("CAPEX_ATIVO").notNull(),
	empresa: text(),
	filial: text(),
	integracaoCodigo: text("integracao_codigo"),
	ativo: integer().default(1).notNull(),
	dataInicio: numeric("data_inicio"),
	dataFim: numeric("data_fim"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const configCentrosCusto = sqliteTable("config_centros_custo", {
	id: integer().primaryKey({ autoIncrement: true }),
	codigo: text().notNull(),
	descricao: text().notNull(),
	empresa: text(),
	filial: text(),
	ativo: integer().default(1).notNull(),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const orcamentoGrupos = sqliteTable("orcamento_grupos", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull(),
	viabilidadeId: integer("viabilidade_id"),
	tipo: text().default("CAPEX_ATIVO").notNull(),
	nome: text().notNull(),
	cor: text(),
	icone: text(),
	ordem: integer().default(0).notNull(),
	ativo: integer().default(1).notNull(),
	criadoPor: integer("criado_por"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const orcamentoItens = sqliteTable("orcamento_itens", {
	id: integer().primaryKey({ autoIncrement: true }),
	grupoId: integer("grupo_id").notNull(),
	projetoId: integer("projeto_id").notNull(),
	nome: text().notNull(),
	descricao: text(),
	contaContabilId: integer("conta_contabil_id"),
	centroCustoId: integer("centro_custo_id"),
	valorAprovado: real("valor_aprovado").notNull(),
	valorRevisado: real("valor_revisado"),
	status: text().default("ATIVO").notNull(),
	prioridade: text().default("MEDIA").notNull(),
	responsavelUsuarioId: integer("responsavel_usuario_id"),
	ordem: integer().default(0).notNull(),
	ativo: integer().default(1).notNull(),
	criadoPor: integer("criado_por"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const financeiroMovimentos = sqliteTable("financeiro_movimentos", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull(),
	itemId: integer("item_id"),
	tipoMovimento: text("tipo_movimento").default("NF").notNull(),
	numeroDoc: text("numero_doc"),
	fornecedor: text(),
	valorTotal: real("valor_total").notNull(),
	dataEmissao: numeric("data_emissao"),
	dataVencimento: numeric("data_vencimento"),
	status: text().default("PENDENTE").notNull(),
	observacoes: text(),
	arquivoPath: text("arquivo_path"),
	criadoPor: integer("criado_por").notNull(),
	aprovadoPor: integer("aprovado_por"),
	aprovadoEm: numeric("aprovado_em"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const financeiroPagamentos = sqliteTable("financeiro_pagamentos", {
	id: integer().primaryKey({ autoIncrement: true }),
	movimentoId: integer("movimento_id").notNull(),
	projetoId: integer("projeto_id").notNull(),
	valorPago: real("valor_pago").notNull(),
	dataPagamento: numeric("data_pagamento").notNull(),
	observacoes: text(),
	criadoPor: integer("criado_por").notNull(),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	contratoId: integer("contrato_id"),
	numeroDocumento: text("numero_documento"),
	tipoDocumento: text("tipo_documento").default("NF"),
	notaFiscal: text("nota_fiscal"),
	competencia: text(),
	arquivoPath: text("arquivo_path"),
	ativo: integer().default(1),
	observacao: text(),
	comprovante: text(),
	enquadramentoStatus: text("enquadramento_status"),
	contratosCandidatos: text("contratos_candidatos"),
	fornecedor: text(),
});

export const projetoTimeline = sqliteTable("projeto_timeline", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull(),
	modulo: text().notNull(),
	artefato: text().notNull(),
	evento: text().notNull(),
	origem: text().default("MANUAL").notNull(),
	titulo: text().notNull(),
	descricao: text(),
	usuarioId: integer("usuario_id"),
	usuarioNome: text("usuario_nome"),
	referenciaId: integer("referencia_id"),
	referenciaTipo: text("referencia_tipo"),
	dadosJson: text("dados_json"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const configCronogramaTipos = sqliteTable("config_cronograma_tipos", {
	id: integer().primaryKey({ autoIncrement: true }),
	codigo: text().notNull(),
	label: text().notNull(),
	ordem: integer().default(0),
	ativo: integer().default(1).notNull(),
	isSystem: integer("is_system").default(0).notNull(),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
});

export const configCronogramaCriticidades = sqliteTable("config_cronograma_criticidades", {
	id: integer().primaryKey({ autoIncrement: true }),
	codigo: text().notNull(),
	label: text().notNull(),
	cor: text().default("#6B7280"),
	ordem: integer().default(0),
	ativo: integer().default(1).notNull(),
	isSystem: integer("is_system").default(0).notNull(),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
});

export const financeiroContratos = sqliteTable("financeiro_contratos", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull(),
	numeroContrato: text("numero_contrato"),
	contratado: text().notNull(),
	tipoContrato: text("tipo_contrato").default("SERVICO").notNull(),
	descricaoServico: text("descricao_servico"),
	valorAprovado: real("valor_aprovado").notNull(),
	status: text().default("ATIVO").notNull(),
	observacoes: text(),
	ativo: integer().default(1).notNull(),
	criadoPor: integer("criado_por"),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
	updatedAt: text("updated_at").default("sql`(datetime('now'))`"),
	observacao: text(),
	naturezaFinanceira: text("natureza_financeira").default("CAPEX").notNull(),
	categoria: text(),
	tipoProjecao: text("tipo_projecao").default("NENHUMA"),
});

export const projetoSnapshotFinal = sqliteTable("projeto_snapshot_final", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull(),
	roiPrevisto: real("roi_previsto"),
	roiAtual: real("roi_atual"),
	capexPrevisto: real("capex_previsto"),
	capexExecutado: real("capex_executado"),
	opexPrevisto: real("opex_previsto"),
	opexExecutado: real("opex_executado"),
	economiaPrevista: real("economia_prevista"),
	economiaRealizada: real("economia_realizada"),
	dataFimPrev: text("data_fim_prev"),
	dataConclusaoReal: text("data_conclusao_real"),
	diasDesvio: integer("dias_desvio"),
	responsavel: text(),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
});

export const configChecklistConclusao = sqliteTable("config_checklist_conclusao", {
	id: integer().primaryKey({ autoIncrement: true }),
	codigo: text().notNull(),
	label: text().notNull(),
	obrigatorio: integer().default(0).notNull(),
	ordem: integer().default(0).notNull(),
	ativo: integer().default(1).notNull(),
});

export const paybackCompetencias = sqliteTable("payback_competencias", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull(),
	ano: integer().notNull(),
	mes: integer().notNull(),
	receita: real().notNull(),
	economia: real().notNull(),
	capex: real().notNull(),
	opex: real().notNull(),
	fluxo: real().notNull(),
	observacao: text(),
	status: text().default("RASCUNHO").notNull(),
	criadoPor: integer("criado_por"),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
	updatedAt: text("updated_at").default("sql`(datetime('now'))`"),
});

export const configMotivosPausa = sqliteTable("config_motivos_pausa", {
	id: integer().primaryKey({ autoIncrement: true }),
	nome: text().notNull(),
	descricao: text(),
	ordem: integer().default(0).notNull(),
	ativo: integer().default(1).notNull(),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
	updatedAt: text("updated_at").default("sql`(datetime('now'))`"),
});

export const cronogramaResponsaveis = sqliteTable("cronograma_responsaveis", {
	id: integer().primaryKey({ autoIncrement: true }),
	cronogramaTarefaId: integer("cronograma_tarefa_id").notNull(),
	usuarioId: integer("usuario_id"),
	usuarioNomeExt: text("usuario_nome_ext"),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
});

export const paybackRegistros = sqliteTable("payback_registros", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull(),
	data: text().notNull(),
	valorReal: real("valor_real").notNull(),
	origem: text().default("manual").notNull(),
	observacao: text(),
	criadoPor: integer("criado_por"),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
});

export const paybackLancamentos = sqliteTable("payback_lancamentos", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	competencia: text().notNull(),
	dataLancamento: text("data_lancamento").notNull(),
	investimentoPeriodo: real("investimento_periodo").notNull(),
	beneficioPeriodo: real("beneficio_periodo").notNull(),
	observacao: text(),
	usuarioId: integer("usuario_id").references(() => usuarios.id),
	usuarioNome: text("usuario_nome"),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
	updatedAt: text("updated_at").default("sql`(datetime('now'))`"),
	tipoBeneficio: text("tipo_beneficio"),
});

export const comiteDecisoes = sqliteTable("comite_decisoes", {
	id: integer().primaryKey({ autoIncrement: true }),
	comiteId: integer("comite_id").notNull().references(() => comites.id),
	projetoId: integer("projeto_id").references(() => projetos.id),
	tipo: text().default("PENDENTE").notNull(),
	descricao: text().notNull(),
	responsavelNome: text("responsavel_nome"),
	prazo: text(),
	status: text().default("PENDENTE"),
	createdBy: integer("created_by").notNull().references(() => usuarios.id),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
	updatedAt: text("updated_at").default("sql`(datetime('now'))`"),
});

export const comitePendencias = sqliteTable("comite_pendencias", {
	id: integer().primaryKey({ autoIncrement: true }),
	comiteId: integer("comite_id").notNull().references(() => comites.id),
	projetoId: integer("projeto_id").references(() => projetos.id),
	descricao: text().notNull(),
	responsavelNome: text("responsavel_nome"),
	prazo: text(),
	status: text().default("ABERTA"),
	createdBy: integer("created_by").notNull().references(() => usuarios.id),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
	resolvedAt: text("resolved_at"),
	resolvedBy: integer("resolved_by").references(() => usuarios.id),
});

export const comiteAta = sqliteTable("comite_ata", {
	id: integer().primaryKey({ autoIncrement: true }),
	comiteId: integer("comite_id").notNull().references(() => comites.id),
	conteudo: text(),
	versao: integer().default(1),
	geradoPorIa: integer("gerado_por_ia").default(0),
	createdBy: integer("created_by").notNull().references(() => usuarios.id),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
	updatedAt: text("updated_at").default("sql`(datetime('now'))`"),
	transcricao: text(),
	conteudoJson: text("conteudo_json"),
	status: text().default("RASCUNHO"),
	horaInicio: text("hora_inicio"),
	horaFim: text("hora_fim"),
	duracaoMin: integer("duracao_min"),
});

export const comiteAtaHistorico = sqliteTable("comite_ata_historico", {
	id: integer().primaryKey({ autoIncrement: true }),
	comiteId: integer("comite_id").notNull().references(() => comites.id),
	ataId: integer("ata_id").notNull().references(() => comiteAta.id),
	versao: integer().notNull(),
	conteudoSnap: text("conteudo_snap"),
	acao: text().notNull(),
	usuarioId: integer("usuario_id").notNull().references(() => usuarios.id),
	usuarioNome: text("usuario_nome"),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
});

export const tiPrioridades = sqliteTable("ti_prioridades", {
	id: integer().primaryKey({ autoIncrement: true }),
	atividadeId: integer("atividade_id").notNull(),
	fonte: text().default("dev2026").notNull(),
	prioridade: integer(),
	confirmada: integer().default(0).notNull(),
	confirmadaEm: text("confirmada_em"),
	confirmadaPor: integer("confirmada_por"),
	confirmadaPorNome: text("confirmada_por_nome"),
	confirmadaComiteId: integer("confirmada_comite_id"),
	solicitacaoAlteracao: integer("solicitacao_alteracao").default(0).notNull(),
	solicitacaoPor: integer("solicitacao_por"),
	solicitacaoPorNome: text("solicitacao_por_nome"),
	solicitacaoEm: text("solicitacao_em"),
	solicitacaoMotivo: text("solicitacao_motivo"),
	solicitacaoNovaPrioridade: integer("solicitacao_nova_prioridade"),
	workflowId: integer("workflow_id"),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
	updatedAt: text("updated_at").default("sql`(datetime('now'))`"),
	projetoId: integer("projeto_id"),
	projetoCodigo: text("projeto_codigo"),
	projetoNome: text("projeto_nome"),
});

export const projetoFasePrazo = sqliteTable("projeto_fase_prazo", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	status: text().notNull(),
	dataLimite: text("data_limite"),
	usuarioId: integer("usuario_id").references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
	dataBaseline: text("data_baseline"),
});

export const projetoFasePrazoHistorico = sqliteTable("projeto_fase_prazo_historico", {
	id: integer().primaryKey({ autoIncrement: true }),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	status: text().notNull(),
	dataAnterior: text("data_anterior").notNull(),
	novaData: text("nova_data").notNull(),
	justificativa: text().notNull(),
	usuarioId: integer("usuario_id").references(() => usuarios.id),
	usuarioNome: text("usuario_nome"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const viabilidadeCapexProjecoes = sqliteTable("viabilidade_capex_projecoes", {
	id: integer().primaryKey({ autoIncrement: true }),
	viabilidadeId: integer("viabilidade_id").notNull().references(() => viabilidade.id),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	periodoRef: text("periodo_ref").notNull(),
	valor: real().notNull(),
	descricao: text().notNull(),
	usuarioId: integer("usuario_id").references(() => usuarios.id),
	usuarioNome: text("usuario_nome"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const financeiroEnquadramentoHistorico = sqliteTable("financeiro_enquadramento_historico", {
	id: integer().primaryKey({ autoIncrement: true }),
	pagamentoId: integer("pagamento_id").notNull(),
	projetoId: integer("projeto_id").notNull(),
	contratoIdAnterior: integer("contrato_id_anterior"),
	contratoIdNovo: integer("contrato_id_novo"),
	tipoAcao: text("tipo_acao").notNull(),
	regraUtilizada: text("regra_utilizada"),
	usuarioId: integer("usuario_id"),
	usuarioNome: text("usuario_nome"),
	createdAt: text("created_at").default("sql`(datetime('now'))`"),
});

export const cronogramaTarefaPagamento = sqliteTable("cronograma_tarefa_pagamento", {
	id: integer().primaryKey({ autoIncrement: true }),
	cronogramaTarefaId: integer("cronograma_tarefa_id").notNull().references(() => cronogramaTarefas.id),
	beneficiario: text(),
	valorTotal: real("valor_total").notNull(),
	qtdParcelas: integer("qtd_parcelas").notNull(),
	periodicidade: text().default("MENSAL").notNull(),
	dataPrimeiraParcela: text("data_primeira_parcela").notNull(),
	financeiroPagamentoId: integer("financeiro_pagamento_id"),
	criadoPor: integer("criado_por").references(() => usuarios.id),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const cronogramaTarefaParcelas = sqliteTable("cronograma_tarefa_parcelas", {
	id: integer().primaryKey({ autoIncrement: true }),
	cronogramaTarefaId: integer("cronograma_tarefa_id").notNull().references(() => cronogramaTarefas.id),
	numero: integer().notNull(),
	valor: real().notNull(),
	dataVencimento: text("data_vencimento").notNull(),
	dataVencimentoBaseline: text("data_vencimento_baseline"),
	status: text().default("PENDENTE").notNull(),
	dataPagamento: text("data_pagamento"),
	pagoPor: integer("pago_por").references(() => usuarios.id),
	financeiroPagamentoId: integer("financeiro_pagamento_id"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const cronogramaTarefaParcelasHistorico = sqliteTable("cronograma_tarefa_parcelas_historico", {
	id: integer().primaryKey({ autoIncrement: true }),
	parcelaId: integer("parcela_id").notNull().references(() => cronogramaTarefaParcelas.id),
	cronogramaTarefaId: integer("cronograma_tarefa_id").notNull().references(() => cronogramaTarefas.id),
	projetoId: integer("projeto_id").notNull().references(() => projetos.id),
	campo: text().notNull(),
	valorAnterior: text("valor_anterior"),
	valorNovo: text("valor_novo"),
	justificativa: text(),
	usuarioId: integer("usuario_id").references(() => usuarios.id),
	usuarioNome: text("usuario_nome"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const financeiroContratoProjecaoParcelas = sqliteTable("financeiro_contrato_projecao_parcelas", {
	id: integer().primaryKey({ autoIncrement: true }),
	contratoId: integer("contrato_id").notNull().references(() => financeiroContratos.id),
	numero: integer().notNull(),
	competencia: text().notNull(),
	valorProjetado: real("valor_projetado").notNull(),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

